### ISSUE TITLE
bash: ./.circleci/semver-check.sh: No such file or directory

### ISSUE THREAD

**Issue by jessethomson** [adierkens/webpack-inject-plugin#17]
**Problem**

Can't install version `1.0.1` of `webpack-inject-plugin`

Running `npm install --save-dev webpack-inject-plugin@1.0.1` gives the error

`bash: ./.circleci/semver-check.sh: No such file or directory`

**Cause**
 
This is in the `package.json`
https://github.com/adierkens/webpack-inject-plugin/blob/1b95265c25951417ed8997e07ad82823f5a6fb9b/package.json#L16

But, the `./.circleci/` folder is ignored by the `.npmignore` file.

**Proposed Fix**

Change `postinstall` to `prepublishOnly` so that the ci only runs before the package is published, and not every time it is installed.

**Comment by adierkens** [comment]
Thanks for the info!
I’ll get a fix in shortly

`1.0.0` should still be good to use in the meantime

**Comment by adierkens** [comment]
Let me know if you hit any problems with `1.0.2`
