### ISSUE TITLE
Feature request: filter files

### ISSUE THREAD

**Issue by hirokiosame** [adierkens/webpack-inject-plugin#22]
I have a build with multiple entry points and I'd like to configure the Inject Plugin to only inject into certain entry-points.

Would like to request that the `entryName` support a regex or function.

**Comment by adierkens** [comment]
That sounds like a great idea! 
I should be able to get something for you later today

**Comment by adierkens** [comment]
Added the ability to use a function as an `entryName` in the config options. Released in `1.4.0`. 
Let me know if you face any issues w/ it

**Comment by hirokiosame** [comment]
Awesome work @adierkens ! Thank you
