### ISSUE TITLE
Plugin authoring and taps

### ISSUE THREAD

**Issue by drolsen** [adierkens/webpack-inject-plugin#33]
What, if any compiler hooks does this plugin work under?

I see this working if ran directly within the apply of a plugin I'm authoring, however if ran within any of the compiler.hooks.***.tap, this plugin does not seem to work.

```js
// Working, but not want I need
apply(compiler) {
  new InjectPlugin(function() {
      return 'console.log("Hello world")';
  }).apply(compiler);
}
```

```js
// What I need, but not working
apply(compiler) {
  compiler.hooks.compilation.tap('MyPlugin', (compilation) => {
    new InjectPlugin(function() {
        return 'console.log("Hello world")';
    }).apply(compiler);
  });
}
```

Am I doing something wrong?

Thank you!

**Comment by adierkens** [comment]
The current way the inject-plugin works, is by adding a new entry point before the webpack compilation is created, hence why your second example isn't working. I'm sure there's probably a way to inject code into the bundle using another tap on the compilation, but that would require some refactoring of the current implementation. 

What's the use-case for requiring the inject-plugin to be within the compilation hook?

**Comment by drolsen** [comment]
> The current way the inject-plugin works, is by adding a new entry point before the webpack compilation is created, hence why your second example isn't working.

Ah, ok that makes sense!

> What's the use-case for requiring the inject-plugin to be within the compilation hook?

- I've got loose src assets files I loop over and compile down to a single new asset file that gets injected into the compilation to be written to disk. No problems here, all working great, but this brings us to the compilation hook I need.
- I inject some followup supporting XHR module code (into a specified entry), that loads up our to new asset from above at page loads in browser.
- Both file written to disk, and XHR url share cache pop hash.

These three things requires me to work within a single hook and that hook be far along enough to do all three above.

I'm only researching ways to clean up my plugins working inject approach; no need to refactor anything unless indeed this turns out to be low effort (then I ask to please consider it).

Thank you!
