### ISSUE TITLE
Add ability to inject code at a specific line number in a module.

### ISSUE THREAD

**Issue by J-Rojas** [adierkens/webpack-inject-plugin#34]
It would be useful to inject code at specific places in a file using this tool, but not with a macro replacement. This would be helpful if you want to inject code into vendor libraries.

I'd imagine you can return an object from the inject function that can specify both the code to inject and the line number.

**Comment by adierkens** [comment]
I would suspect adding support for injecting code into specific files/lines would require a significant re-architecture or the plugin, as it currently only mimics adding in another entry point to your bundle.

Have you seen [patch-package](https://github.com/ds300/patch-package)? That might be an option for you.

**Comment by J-Rojas** [comment]
Okay, thanks for the recommendation. patch-package does look like a better solution for this. So you're suggestion is to run the patch-package as part of the build to modify any bundled modules before proceeding with the normal webpack build, correct? Is there also a way to patch code into project code as well for production builds?

**Comment by adierkens** [comment]
> So your suggestion is to run the patch-package as part of the build to modify any bundled modules before proceeding with the normal webpack build, correct?

Yeah, that's probably the route I would take if I needed to modify specific lines of code in a dependency. 

>  Is there also a way to patch code into project code as well for production builds?

Is there more you can share about your use-case for injecting code into a production bundle? The typical use cases for the `webpack-inject-plugin` I've seen involve calling public APIs to register/setup stuff -- and often-times it's used within another plugin that can read from a config file or similar. 

If you're looking to modify your own source files based on bundling or not, perhaps you can use something like `process.env.NODE_ENV === 'production'` which can be tree-shaken when bundling.

**Comment by J-Rojas** [comment]
Thanks for the suggestions. I will close this feature request and use `patch-package`.
