### ISSUE TITLE
Access to Loader scope

### ISSUE THREAD

**Issue by emily-ellevation** [adierkens/webpack-inject-plugin#35]
Not sure if I'm missing something but the README mentions that the callback supplied to the plugin is invoked with the same scope as 'loader' but `this` in the function is an empty object. Am I missing something? How do I access loader properties?

**Comment by adierkens** [comment]
Looks like that no longer applies after the change to support multiple instances: https://github.com/adierkens/webpack-inject-plugin/pull/21

I'll update the documentation to reflect that. 

What specific loader options where you looking for? Maybe we can find a way to better expose the loading context.

**Comment by emily-ellevation** [comment]
There may be an easier way to do this but I'm trying to inject a piece of code that would change depending on the entry being compiled so I was thinking `this._module` but the `this.request` might be enough as I may only need the file name.

**Comment by adierkens** [comment]
Just got around to testing this, and it does look like we're passing the loader options along correctly. You can test this by modifying the example to `console.log` out the loaderOptions.

```javascript
const InjectPlugin = require('..').default;
const loaderUtils = require('loader-utils');

module.exports = {
  entry: './entry.js',
  mode: 'development',
  plugins: [
    new InjectPlugin(function() {
      const options = loaderUtils.getOptions(this);
      console.log('loaderOptions', options);
      console.log('module', this._module);
      return `console.log('hello world');`;
    }),
    new InjectPlugin(() => `console.log('second injected code');`)
  ]
};
```

And it logs out the info correctly:

![Screen Shot 2019-10-04 at 1 06 57 AM](https://user-images.githubusercontent.com/13004162/66191492-49fc9c80-e643-11e9-85bc-c342b5732dc5.png)

Double check that you're not using an arrow function in the callback, as that will bind the function to a different scope, which will break the `this` from being set correctly

**Comment by emily-ellevation** [comment]
Doh! Definitely was using an arrow function -- that makes a lot of sense. Thank you for investigating.
