### ISSUE TITLE
Module parse failed: Octal literal in strict mode

### ISSUE THREAD

**Issue by ppiyush13** [adierkens/webpack-inject-plugin#43]
Hi,

I am using **webpack-inject-plugin** plugin to generate following module content:

```js
new InjectPlugin(
            () => `
                export default () => import('E:\\node\\cra-external-import\\node_modules\\.pnpm\\registry.npmjs.org\\react-dev-utils\\10.0.0\\node_modules\\react-dev-utils\\webpackHotDevClient.js')
            `,
        );
```

After doing so I am facing this issue:

```
E:/node/cra-external-import/node_modules/.pnpm/registry.npmjs.org/webpack-inject-plugin/1.5.4/node_modules/webpack-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1 3:105
Module parse failed: Octal literal in strict mode (3:105)
File was processed with these loaders:
 * ../../node_modules/.pnpm/registry.npmjs.org/webpack-inject-plugin/1.5.4/node_modules/webpack-inject-plugin/dist/webpack-inject-plugin.loader.js
You may need an additional loader to handle the result of these loaders.
|
|                 export default () =>
>                 import('E:\node\cra-external-import\node_modules\.pnpm\registry.npmjs.org\react-dev-utils\10.0.0\node_modules\react-dev-utils\webpackHotDevClient.js')
|
```

I think its failing due to presence of ```10.0.0``` in the module content, for which babel is throwing error.  
I am using PNPM monorepo because of which I am getting this folder structure. 

Is this issue with plugin or I have missed something ?

**Comment by adierkens** [comment]
The problem you're facing is most likely the presence of `\1` which is getting interpreted as an [octal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_octal) and isn't allowed in `strict` mode. 

I don't think it's an issue with the plugin at all.

**Comment by ppiyush13** [comment]
Thanks @adierkens for quick reply. 
I searched around and you are right this is not an issue with the plugin itself.
I resolved this issue by escaping using https://www.npmjs.com/package/jsesc npm library. 

I am closing this issue as it is not an actual issue with plugin.
